In [1]:
import pandas as pd
import os

In [2]:
#import table 4 file
df = pd.read_csv(r'../raw_data/Table04_TFW_Positive_LMIAs_By_NOC_SkillLevel_Province_2016_2023.csv', encoding='ISO-8859-1')
df.tail(20)

,"Number of temporary foreign worker (TFW) positions on positive Labour Market Impact Assessments (LMIAs) by National Occupational Classification - 2011 (NOC) skill level and management group of occupations, and province/territory",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
99,A - Professionals,1,1,0,1,0,0,1,1
100,B - Skilled and Technical,24,24,8,31,19,15,87,54
101,C - Intermediate and Clerical,36,18,12,13,9,6,2,15
102,D - Elemental and Labourers,0,1,0,6,1,7,38,52
103,Northwest Territories - Total,64,46,21,56,29,30,132,124
104,Nunavut,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023
106,0 - Management Occupations,2,1,4,0,1,0,2,0
107,A - Professionals,7,14,8,1,0,5,0,3
108,B - Skilled and Technical,31,10,57,71,29,43,56,84
109,C - Intermediate and Clerical,102,16,50,58,15,13,18,25
110,D - Elemental and Labourers,3,0,13,3,1,2,12,10
111,Nunavut - Total,145,41,132,133,46,63,88,122
112,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,1. The source for all information in this rele...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,"2. Effective November 2016, NOC 2011 is being ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,3. Each LMIA application submitted is restrict...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,"4. The LMIA System tracks TFW positions only, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,5. The numbers appearing in this release may d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,6. As of the publication of 2023 annual data (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df = df.iloc[:-7]
df.head(20)

,"Number of temporary foreign worker (TFW) positions on positive Labour Market Impact Assessments (LMIAs) by National Occupational Classification - 2011 (NOC) skill level and management group of occupations, and province/territory",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023
2,0 - Management Occupations,"1,913","1,752","1,508","2,245","2,721","2,608","4,041","4,663"
3,A - Professionals,"4,554","3,835","4,293","5,901","5,095","6,445","11,388","8,970"
4,B - Skilled and Technical,"19,094","19,454","18,980","29,411","26,303","27,517","62,999","67,068"
5,C - Intermediate and Clerical,"61,572","69,152","79,759","85,308","82,967","88,146","116,274","127,850"
6,D - Elemental and Labourers,"3,181","3,953","4,448","7,587","8,187","8,479","28,140","31,084"
7,Canada - Total,"90,314","98,146","108,988","130,457","125,279","133,196","222,847","239,646"
8,Newfoundland and Labrador,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023
10,0 - Management Occupations,75,34,14,9,17,23,11,14
11,A - Professionals,147,84,21,55,43,48,45,54
12,B - Skilled and Technical,"1,126",787,321,308,529,401,561,387
13,C - Intermediate and Clerical,333,301,119,110,180,199,493,701
14,D - Elemental and Labourers,60,11,2,13,158,23,343,512
15,Newfoundland and Labrador - Total,"1,741","1,217",477,495,927,694,"1,453","1,668"
16,Prince Edward Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023
18,0 - Management Occupations,9,4,4,3,9,7,4,6
19,A - Professionals,42,11,2,5,6,3,8,4

In [4]:
#Rename the first column
df.rename(columns={'Number of temporary foreign worker (TFW) positions on positive Labour Market Impact Assessments (LMIAs) by National Occupational Classification - 2011 (NOC) skill level and management group of occupations, and province/territory': 'province_region'}, inplace=True)

In [5]:
df.head(20)

,province_region,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023
2,0 - Management Occupations,"1,913","1,752","1,508","2,245","2,721","2,608","4,041","4,663"
3,A - Professionals,"4,554","3,835","4,293","5,901","5,095","6,445","11,388","8,970"
4,B - Skilled and Technical,"19,094","19,454","18,980","29,411","26,303","27,517","62,999","67,068"
5,C - Intermediate and Clerical,"61,572","69,152","79,759","85,308","82,967","88,146","116,274","127,850"
6,D - Elemental and Labourers,"3,181","3,953","4,448","7,587","8,187","8,479","28,140","31,084"
7,Canada - Total,"90,314","98,146","108,988","130,457","125,279","133,196","222,847","239,646"
8,Newfoundland and Labrador,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023
10,0 - Management Occupations,75,34,14,9,17,23,11,14
11,A - Professionals,147,84,21,55,43,48,45,54
12,B - Skilled and Technical,"1,126",787,321,308,529,401,561,387
13,C - Intermediate and Clerical,333,301,119,110,180,199,493,701
14,D - Elemental and Labourers,60,11,2,13,158,23,343,512
15,Newfoundland and Labrador - Total,"1,741","1,217",477,495,927,694,"1,453","1,668"
16,Prince Edward Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023
18,0 - Management Occupations,9,4,4,3,9,7,4,6
19,A - Professionals,42,11,2,5,6,3,8,4

In [6]:
# Identify the row that contains headers and use it as the new header
header_row_index = df[df['province_region'].str.contains('Management Occupations', na=False)].index[0]
new_headers = df.loc[header_row_index]
df.columns = new_headers
df.head(10)

1,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023
0,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023
2,0 - Management Occupations,"1,913","1,752","1,508","2,245","2,721","2,608","4,041","4,663"
3,A - Professionals,"4,554","3,835","4,293","5,901","5,095","6,445","11,388","8,970"
4,B - Skilled and Technical,"19,094","19,454","18,980","29,411","26,303","27,517","62,999","67,068"
5,C - Intermediate and Clerical,"61,572","69,152","79,759","85,308","82,967","88,146","116,274","127,850"
6,D - Elemental and Labourers,"3,181","3,953","4,448","7,587","8,187","8,479","28,140","31,084"
7,Canada - Total,"90,314","98,146","108,988","130,457","125,279","133,196","222,847","239,646"
8,Newfoundland and Labrador,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023

In [7]:
# Drop the header rows after setting them
df = df.drop(header_row_index)
df.head(20)

1,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023
0,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0 - Management Occupations,"1,913","1,752","1,508","2,245","2,721","2,608","4,041","4,663"
3,A - Professionals,"4,554","3,835","4,293","5,901","5,095","6,445","11,388","8,970"
4,B - Skilled and Technical,"19,094","19,454","18,980","29,411","26,303","27,517","62,999","67,068"
5,C - Intermediate and Clerical,"61,572","69,152","79,759","85,308","82,967","88,146","116,274","127,850"
6,D - Elemental and Labourers,"3,181","3,953","4,448","7,587","8,187","8,479","28,140","31,084"
7,Canada - Total,"90,314","98,146","108,988","130,457","125,279","133,196","222,847","239,646"
8,Newfoundland and Labrador,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023
10,0 - Management Occupations,75,34,14,9,17,23,11,14
11,A - Professionals,147,84,21,55,43,48,45,54
12,B - Skilled and Technical,"1,126",787,321,308,529,401,561,387
13,C - Intermediate and Clerical,333,301,119,110,180,199,493,701
14,D - Elemental and Labourers,60,11,2,13,158,23,343,512
15,Newfoundland and Labrador - Total,"1,741","1,217",477,495,927,694,"1,453","1,668"
16,Prince Edward Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023
18,0 - Management Occupations,9,4,4,3,9,7,4,6
19,A - Professionals,42,11,2,5,6,3,8,4
20,B - Skilled and Technical,53,57,22,48,50,51,140,120

In [8]:
#Create a new column for province/region name
# Identify rows where 'Unnamed: 1' is NaN (indicating region rows) and exclude rows containing 'Total'
df['province_region'] = df['Management Occupations and Skill Level (A - D)'].where(df['2016'].isna() & ~df['Management Occupations and Skill Level (A - D)'].str.contains('Total', na=False))
#  Forward-fill the region name for all rows until a new region is found
df['province_region'] = df['province_region'].ffill()
#  Remove rows that contain "Total" adn Nan value (since these are summary rows)
df = df[~df['Management Occupations and Skill Level (A - D)'].str.contains('Total', na=False)]

In [9]:
df.head(20)

1,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023,province_region
0,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada
2,0 - Management Occupations,"1,913","1,752","1,508","2,245","2,721","2,608","4,041","4,663",Canada
3,A - Professionals,"4,554","3,835","4,293","5,901","5,095","6,445","11,388","8,970",Canada
4,B - Skilled and Technical,"19,094","19,454","18,980","29,411","26,303","27,517","62,999","67,068",Canada
5,C - Intermediate and Clerical,"61,572","69,152","79,759","85,308","82,967","88,146","116,274","127,850",Canada
6,D - Elemental and Labourers,"3,181","3,953","4,448","7,587","8,187","8,479","28,140","31,084",Canada
8,Newfoundland and Labrador,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Newfoundland and Labrador
9,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023,Newfoundland and Labrador
10,0 - Management Occupations,75,34,14,9,17,23,11,14,Newfoundland and Labrador
11,A - Professionals,147,84,21,55,43,48,45,54,Newfoundland and Labrador
12,B - Skilled and Technical,"1,126",787,321,308,529,401,561,387,Newfoundland and Labrador
13,C - Intermediate and Clerical,333,301,119,110,180,199,493,701,Newfoundland and Labrador
14,D - Elemental and Labourers,60,11,2,13,158,23,343,512,Newfoundland and Labrador
16,Prince Edward Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prince Edward Island
17,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023,Prince Edward Island
18,0 - Management Occupations,9,4,4,3,9,7,4,6,Prince Edward Island
19,A - Professionals,42,11,2,5,6,3,8,4,Prince Edward Island
20,B - Skilled and Technical,53,57,22,48,50,51,140,120,Prince Edward Island
21,C - Intermediate and Clerical,795,962,980,"1,107","1,641","1,356","1,962","1,372",Prince Edward Island
22,D - Elemental and Labourers,47,22,4,16,18,87,177,209,Prince Edward Island

In [10]:
# The rows after region names have NaN values for the year columns
df = df.dropna(subset=['2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023'], how='all')
df.head(20)

1,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023,province_region
2,0 - Management Occupations,"1,913","1,752","1,508","2,245","2,721","2,608","4,041","4,663",Canada
3,A - Professionals,"4,554","3,835","4,293","5,901","5,095","6,445","11,388","8,970",Canada
4,B - Skilled and Technical,"19,094","19,454","18,980","29,411","26,303","27,517","62,999","67,068",Canada
5,C - Intermediate and Clerical,"61,572","69,152","79,759","85,308","82,967","88,146","116,274","127,850",Canada
6,D - Elemental and Labourers,"3,181","3,953","4,448","7,587","8,187","8,479","28,140","31,084",Canada
9,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023,Newfoundland and Labrador
10,0 - Management Occupations,75,34,14,9,17,23,11,14,Newfoundland and Labrador
11,A - Professionals,147,84,21,55,43,48,45,54,Newfoundland and Labrador
12,B - Skilled and Technical,"1,126",787,321,308,529,401,561,387,Newfoundland and Labrador
13,C - Intermediate and Clerical,333,301,119,110,180,199,493,701,Newfoundland and Labrador
14,D - Elemental and Labourers,60,11,2,13,158,23,343,512,Newfoundland and Labrador
17,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023,Prince Edward Island
18,0 - Management Occupations,9,4,4,3,9,7,4,6,Prince Edward Island
19,A - Professionals,42,11,2,5,6,3,8,4,Prince Edward Island
20,B - Skilled and Technical,53,57,22,48,50,51,140,120,Prince Edward Island
21,C - Intermediate and Clerical,795,962,980,"1,107","1,641","1,356","1,962","1,372",Prince Edward Island
22,D - Elemental and Labourers,47,22,4,16,18,87,177,209,Prince Edward Island
25,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023,Nova Scotia
26,0 - Management Occupations,52,60,43,42,48,44,56,54,Nova Scotia
27,A - Professionals,130,70,65,63,55,119,163,97,Nova Scotia

In [11]:
df = df[df['Management Occupations and Skill Level (A - D)'] != 'Management Occupations and Skill Level (A - D)']
df.head(20)

1,Management Occupations and Skill Level (A - D),2016,2017,2018,2019,2020,2021,2022,2023,province_region
2,0 - Management Occupations,"1,913","1,752","1,508","2,245","2,721","2,608","4,041","4,663",Canada
3,A - Professionals,"4,554","3,835","4,293","5,901","5,095","6,445","11,388","8,970",Canada
4,B - Skilled and Technical,"19,094","19,454","18,980","29,411","26,303","27,517","62,999","67,068",Canada
5,C - Intermediate and Clerical,"61,572","69,152","79,759","85,308","82,967","88,146","116,274","127,850",Canada
6,D - Elemental and Labourers,"3,181","3,953","4,448","7,587","8,187","8,479","28,140","31,084",Canada
10,0 - Management Occupations,75,34,14,9,17,23,11,14,Newfoundland and Labrador
11,A - Professionals,147,84,21,55,43,48,45,54,Newfoundland and Labrador
12,B - Skilled and Technical,"1,126",787,321,308,529,401,561,387,Newfoundland and Labrador
13,C - Intermediate and Clerical,333,301,119,110,180,199,493,701,Newfoundland and Labrador
14,D - Elemental and Labourers,60,11,2,13,158,23,343,512,Newfoundland and Labrador
18,0 - Management Occupations,9,4,4,3,9,7,4,6,Prince Edward Island
19,A - Professionals,42,11,2,5,6,3,8,4,Prince Edward Island
20,B - Skilled and Technical,53,57,22,48,50,51,140,120,Prince Edward Island
21,C - Intermediate and Clerical,795,962,980,"1,107","1,641","1,356","1,962","1,372",Prince Edward Island
22,D - Elemental and Labourers,47,22,4,16,18,87,177,209,Prince Edward Island
26,0 - Management Occupations,52,60,43,42,48,44,56,54,Nova Scotia
27,A - Professionals,130,70,65,63,55,119,163,97,Nova Scotia
28,B - Skilled and Technical,412,284,188,244,190,244,677,664,Nova Scotia
29,C - Intermediate and Clerical,"1,762","2,176","3,024","2,340","2,783","3,454","4,129","3,596",Nova Scotia
30,D - Elemental and Labourers,100,113,74,134,183,300,567,"1,025",Nova Scotia

In [12]:
# Split the column 'Management Occupations and Skill Level (A - D)' into 'skill_level' and 'occupation'
df[['skill_level', 'occupation']] = df['Management Occupations and Skill Level (A - D)'].str.extract(r'(\w+) - (.*)')

# Drop the original column after splitting
df = df.drop(columns=['Management Occupations and Skill Level (A - D)'])

In [13]:
df.head(5)

1,2016,2017,2018,2019,2020,2021,2022,2023,province_region,skill_level,occupation
2,"1,913","1,752","1,508","2,245","2,721","2,608","4,041","4,663",Canada,0,Management Occupations
3,"4,554","3,835","4,293","5,901","5,095","6,445","11,388","8,970",Canada,A,Professionals
4,"19,094","19,454","18,980","29,411","26,303","27,517","62,999","67,068",Canada,B,Skilled and Technical
5,"61,572","69,152","79,759","85,308","82,967","88,146","116,274","127,850",Canada,C,Intermediate and Clerical
6,"3,181","3,953","4,448","7,587","8,187","8,479","28,140","31,084",Canada,D,Elemental and Labourers

In [14]:
# Define the desired column order
desired_order = ['province_region', 'occupation','skill_level', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023']
# Reorder the DataFrame using the desired column order
df = df[desired_order]

In [15]:
df.head()

1,province_region,occupation,skill_level,2016,2017,2018,2019,2020,2021,2022,2023
2,Canada,Management Occupations,0,"1,913","1,752","1,508","2,245","2,721","2,608","4,041","4,663"
3,Canada,Professionals,A,"4,554","3,835","4,293","5,901","5,095","6,445","11,388","8,970"
4,Canada,Skilled and Technical,B,"19,094","19,454","18,980","29,411","26,303","27,517","62,999","67,068"
5,Canada,Intermediate and Clerical,C,"61,572","69,152","79,759","85,308","82,967","88,146","116,274","127,850"
6,Canada,Elemental and Labourers,D,"3,181","3,953","4,448","7,587","8,187","8,479","28,140","31,084"

In [16]:
#Define the dedicated folder path
folder_path = 'C:/Users/Johnn/Desktop/Data Engineer project/LMIA_evaluation_project/clean_data'
csv_file = os.path.join(folder_path, 'lmia_tfw_positions_noc_level_prov.csv')

# Save the DataFrame to CSV
df.to_csv(csv_file, index=False)