In [13]:
import pandas as pd
import os

In [14]:
df = pd.read_csv(r'../raw_data/Table12_TFW_Positions_Requested_LMIAs_Province_2016_2023.csv', encoding='ISO-8859-1',skiprows=1)
df.tail(20)

,Province/Territory,2016,2017,2018,2019,2020,2021,2022,2023
1,Prince Edward Island,979,"1,246","1,066","1,413","2,008","1,734","1,921","1,855"
2,Nova Scotia,"2,531","3,504","3,134","3,187","3,663","4,102","5,628","5,677"
3,New Brunswick,"1,648","1,664","1,936","2,140","3,205","3,726","6,967","5,792"
4,Quebec,"17,107","20,934","28,046","32,905","33,964","42,650","63,685","65,581"
5,Ontario,"36,729","44,685","42,247","43,862","47,132","50,100","62,064","83,403"
6,Manitoba,"1,455","1,610","2,106","1,978","1,880","2,525","4,255","5,983"
7,Saskatchewan,"1,256","1,272","1,622","1,521","1,344","1,524","2,561","4,027"
8,Alberta,"13,115","10,650","13,264","12,447","10,532","12,920","24,597","37,378"
9,British Columbia,"26,117","26,608","37,466","31,815","35,407","38,076","48,690","64,923"
10,Yukon,126,129,123,146,61,138,168,167
11,Northwest Territories,79,68,64,58,28,76,105,211
12,Nunavut,156,44,141,136,46,84,77,146
13,Canada,"103,232","113,603","131,748","132,472","140,014","158,724","222,078","277,095"
14,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1. The source for all information in this rele...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2. The sum of the number of TFW positions by p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,3. Employers may only submit one LMIA applicat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,"4. The LMIA System tracks TFW positions only, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,5. The numbers appearing in this release may d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,6. As of the publication of 2023 annual data (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df = df.iloc[:-7]

In [16]:
df.tail()

,Province/Territory,2016,2017,2018,2019,2020,2021,2022,2023
9,British Columbia,"26,117","26,608","37,466","31,815","35,407","38,076","48,690","64,923"
10,Yukon,126,129,123,146,61,138,168,167
11,Northwest Territories,79,68,64,58,28,76,105,211
12,Nunavut,156,44,141,136,46,84,77,146
13,Canada,"103,232","113,603","131,748","132,472","140,014","158,724","222,078","277,095"

In [17]:
df

,Province/Territory,2016,2017,2018,2019,2020,2021,2022,2023
0,Newfoundland and Labrador,"1,912","1,175",533,864,744,"1,069","1,360","1,952"
1,Prince Edward Island,979,"1,246","1,066","1,413","2,008","1,734","1,921","1,855"
2,Nova Scotia,"2,531","3,504","3,134","3,187","3,663","4,102","5,628","5,677"
3,New Brunswick,"1,648","1,664","1,936","2,140","3,205","3,726","6,967","5,792"
4,Quebec,"17,107","20,934","28,046","32,905","33,964","42,650","63,685","65,581"
5,Ontario,"36,729","44,685","42,247","43,862","47,132","50,100","62,064","83,403"
6,Manitoba,"1,455","1,610","2,106","1,978","1,880","2,525","4,255","5,983"
7,Saskatchewan,"1,256","1,272","1,622","1,521","1,344","1,524","2,561","4,027"
8,Alberta,"13,115","10,650","13,264","12,447","10,532","12,920","24,597","37,378"
9,British Columbia,"26,117","26,608","37,466","31,815","35,407","38,076","48,690","64,923"
10,Yukon,126,129,123,146,61,138,168,167
11,Northwest Territories,79,68,64,58,28,76,105,211
12,Nunavut,156,44,141,136,46,84,77,146
13,Canada,"103,232","113,603","131,748","132,472","140,014","158,724","222,078","277,095"

In [18]:
df.rename(columns={'Province/Territory':'Province_Territory'}, inplace=True)

In [19]:
df

,Province_Territory,2016,2017,2018,2019,2020,2021,2022,2023
0,Newfoundland and Labrador,"1,912","1,175",533,864,744,"1,069","1,360","1,952"
1,Prince Edward Island,979,"1,246","1,066","1,413","2,008","1,734","1,921","1,855"
2,Nova Scotia,"2,531","3,504","3,134","3,187","3,663","4,102","5,628","5,677"
3,New Brunswick,"1,648","1,664","1,936","2,140","3,205","3,726","6,967","5,792"
4,Quebec,"17,107","20,934","28,046","32,905","33,964","42,650","63,685","65,581"
5,Ontario,"36,729","44,685","42,247","43,862","47,132","50,100","62,064","83,403"
6,Manitoba,"1,455","1,610","2,106","1,978","1,880","2,525","4,255","5,983"
7,Saskatchewan,"1,256","1,272","1,622","1,521","1,344","1,524","2,561","4,027"
8,Alberta,"13,115","10,650","13,264","12,447","10,532","12,920","24,597","37,378"
9,British Columbia,"26,117","26,608","37,466","31,815","35,407","38,076","48,690","64,923"
10,Yukon,126,129,123,146,61,138,168,167
11,Northwest Territories,79,68,64,58,28,76,105,211
12,Nunavut,156,44,141,136,46,84,77,146
13,Canada,"103,232","113,603","131,748","132,472","140,014","158,724","222,078","277,095"

In [20]:
#Define the dedicated folder path
folder_path = 'C:/Users/Johnn/Desktop/Data Engineer project/LMIA_evaluation_project/clean_data'
csv_file = os.path.join(folder_path, 'Table12_TFW_Positions_Requested_LMIAs_Province_2016_2023_cleaned.csv')

# Save the DataFrame to CSV
df.to_csv(csv_file, index=False)